/**
 * Generates src/content/covers.ts: a 1:1 mapping from each reading to a unique
 * bundled business photo (no repeats), with any leftovers as a fallback pool.
 *
 *   npx tsx scripts/gen-covers.ts
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { ALL_READINGS } from '../src/content/index';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const COVERS_DIR = path.resolve(__dirname, '../assets/covers');

const images = fs
  .readdirSync(COVERS_DIR)
  .filter((f) => f.startsWith('biz-') && f.endsWith('.jpg'))
  .sort();

const ids = ALL_READINGS.map((r) => r.id);
if (images.length < ids.length) {
  console.error(`Only ${images.length} images for ${ids.length} readings.`);
  process.exit(1);
}

const lines: string[] = [];
lines.push("import { ImageSourcePropType } from 'react-native';");
lines.push('');
lines.push('// AUTO-GENERATED by scripts/gen-covers.ts. 1:1 reading -> unique photo.');
lines.push('const MAP: Record<string, ImageSourcePropType> = {');
ids.forEach((id, i) => {
  lines.push(`  ${JSON.stringify(id)}: require('../../assets/covers/${images[i]}'),`);
});
lines.push('};');
lines.push('');
lines.push('const FALLBACK: ImageSourcePropType[] = [');
images.slice(ids.length).forEach((img) => {
  lines.push(`  require('../../assets/covers/${img}'),`);
});
// if no leftovers, fall back to the first few mapped images
if (images.length === ids.length) {
  images.slice(0, 6).forEach((img) => {
    lines.push(`  require('../../assets/covers/${img}'),`);
  });
}
lines.push('];');
lines.push('');
lines.push('function hash(s: string): number {');
lines.push('  let h = 0;');
lines.push('  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) >>> 0;');
lines.push('  return h;');
lines.push('}');
lines.push('');
lines.push('/** A stable, unique cover image for each reading. */');
lines.push('export function coverFor(id: string): ImageSourcePropType {');
lines.push('  return MAP[id] ?? FALLBACK[hash(id) % FALLBACK.length];');
lines.push('}');
lines.push('');

fs.writeFileSync(path.resolve(__dirname, '../src/content/covers.ts'), lines.join('\n'));
console.log(`Wrote covers.ts: ${ids.length} mapped, ${images.length - ids.length} fallback.`);
